name = "TestPackage"
uuid = "8c046de1-9596-4d15-8be4-f4127fa9b588"
authors = ["Knut Andreas Meyer and contributors"]
version = "0.1.0"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestPackageTestUtils = "226c0c43-94e1-4a27-8c15-9767de209b08"

[targets]
test = ["Test", "TestPackageTestUtils"]

[sources]
TestPackageTestUtils = {path = "test/TestPackageTestUtils"}
